service: serverless-tutorial

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-southeast-2
  stage: ${opt:stage , 'dev'}
  apiGateway:
    shouldStartNameWithService: true
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        Fn::GetAtt:
          - OrdersTable
          - Arn
  environment:
    orderTableName: ${self:custom.orderTableName}

custom:
  orderTableName: orders-table-${self:provider.stage}

functions:
  createOrder:
    handler: src/lambdas/create-order.handler
    events:
      - http:
          method: POST
          path: /orders/create-order
          cors: true
  getOrder:
    handler: src/lambdas/get-order.handler
    events:
      - http:
          method: GET
          path: /orders/get-order/{id}
          cors: true



resources:
 Resources:
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: ${self:custom.orderTableName}
   
