service: serverless-tutorial

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-southeast-2
  stage: ${opt:stage , 'dev'}
  apiGateway:
    shouldStartNameWithService: true
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        Fn::GetAtt:
          - OrdersTable
          - Arn
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - 'Ref': 'OrdersBucket'
            - '/*'
  environment:
    orderTableName: ${self:custom.orderTableName}
    ordersBucketName: ${self:custom.ordersBucketName}

custom:
  orderTableName: orders-table-${self:provider.stage}
  ordersBucketName: sls-tut-arabic-orders-bucket-${self:provider.stage}

functions:
  createOrder:
    handler: src/lambdas/create-order.handler
    events:
      - http:
          method: POST
          path: /orders/create-order
          cors: true
  getOrder:
    handler: src/lambdas/get-order.handler
    events:
      - http:
          method: GET
          path: /orders/get-order/{id}
          cors: true
  orderProcessor:
    handler: src/lambdas/order-processor.handler
    events:
      - s3:
          bucket: ${self:custom.ordersBucketName}
          event: s3:ObjectCreated:*
          existing: true



resources:
 Resources:
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: ${self:custom.orderTableName}
  OrdersBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.ordersBucketName}
   
